source 'https://rubygems.org'

gem 'rails', '4.0.0.rc1'
gem 'protected_attributes'
gem 'sass-rails', '~> 4.0.0.rc1'
gem 'uglifier', '>= 1.3.0'
gem 'redis'
gem 'figaro'

group :production do 
  gem 'pg'
end

group :development, :test do
  gem 'sqlite3'
  gem 'rspec-rails', '~> 2.0'
  gem 'capybara'
  gem 'guard-rspec'
  gem 'launchy'
end

group :test do 
  gem 'vcr'
  gem 'webmock'
end


gem 'coffee-rails', '~> 4.0.0'

gem 'jquery-rails'

gem 'turbolinks'

gem 'jbuilder', '~> 1.0.1'

group :doc do
  gem 'sdoc', require: false
end
